[package]
edition = "2021"
name = "wisp"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
bytemuck = {version = "1.9.1", features = ["derive"]}
leb128 = "0.2.5"
thiserror = "1.0.31"
